import { ApiPropertyOptional, PartialType } from '@nestjs/swagger';
import { DealState } from '@prisma/client';
import {
  IsDateString,
  IsEnum,
  IsOptional,
  IsString,
  MaxLength,
} from 'class-validator';
import { CreateDealDto } from './create-deal.dto';

export class UpdateDealDto extends PartialType(CreateDealDto) {
  @ApiPropertyOptional({
    description: 'Updated state for the escrow deal lifecycle',
    enum: DealState,
    example: DealState.DEPOSITED,
  })
  @IsOptional()
  @IsEnum(DealState, { message: 'Invalid deal state' })
  state?: DealState;

  @ApiPropertyOptional({
    description: 'Settlement transaction hash on-chain',
    example:
      '0x5a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef',
  })
  @IsOptional()
  @IsString({ message: 'Settle transaction hash must be a string' })
  @MaxLength(66, {
    message: 'Settle transaction hash must not exceed 66 characters',
  })
  settleTxHash?: string;

  @ApiPropertyOptional({
    description: 'Dispute arbitration transaction hash on-chain',
    example:
      '0x9f8e7d6c5b4a3210fedcba9876543210fedcba9876543210fedcba9876543210',
  })
  @IsOptional()
  @IsString({ message: 'Dispute transaction hash must be a string' })
  @MaxLength(66, {
    message: 'Dispute transaction hash must not exceed 66 characters',
  })
  disputeTxHash?: string;

  @ApiPropertyOptional({
    description: 'Timestamp when escrow funds were locked in ISO-8601 format',
    example: '2026-09-26T03:30:00.000Z',
  })
  @IsOptional()
  @IsDateString({}, { message: 'Deposited at must be an ISO date-time string' })
  depositedAt?: string;

  @ApiPropertyOptional({
    description:
      'Inspection deadline timestamp after which buyer auto-accepts or funds release',
    example: '2026-09-30T12:00:00.000Z',
  })
  @IsOptional()
  @IsDateString(
    {},
    { message: 'Inspection deadline must be an ISO date-time string' },
  )
  inspectionDeadline?: string;

  @ApiPropertyOptional({
    description:
      'Payment order code generated by PayOS or Banking gateway for reconciliation',
    example: 88990011,
  })
  @IsOptional()
  paymentOrderCode?: string | number | bigint;

  @ApiPropertyOptional({
    description: 'External payment reference transaction identifier',
    example: 'PAYOS_REF_998877',
  })
  @IsOptional()
  @IsString({ message: 'Payment ref ID must be a string' })
  @MaxLength(100, { message: 'Payment ref ID must not exceed 100 characters' })
  paymentRefId?: string;

  @ApiPropertyOptional({
    description:
      'Idempotency key associated with payment webhook to avoid double processing',
    example: 'hook_idemp_99887766',
  })
  @IsOptional()
  @IsString({ message: 'Webhook idempotency key must be a string' })
  @MaxLength(128, {
    message: 'Webhook idempotency key must not exceed 128 characters',
  })
  webhookIdempotencyKey?: string;
}
