pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

plugins {
    // Plugin Foojay tự động tải OpenJDK tương thích về cache Gradle
    id "org.gradle.toolchains.foojay-resolver-convention" version "0.8.0"
}

rootProject.name = 'mb_user'
include ':app'
