[build]
  command = "npm run build --workspace=cl_user"
  publish = "apps/cl_user/.next"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps --include=dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"

