[build]
  command = "npm run build --workspace=cl_user"
  publish = "apps/cl_user/.next"

[build.environment]
  NODE_ENV = "development"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"
